# Generated by Django 3.1.4 on 2020-12-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminstuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_room', models.CharField(blank=True, max_length=100)),
                ('room_description', models.CharField(blank=True, max_length=100)),
                ('FIELDNAME', models.ImageField(upload_to='pics')),
                ('Price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
