# Generated by Django 3.1.4 on 2020-12-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminstuff',
            old_name='FIELDNAME',
            new_name='image',
        ),
    ]
