# Generated by Django 3.1.4 on 2020-12-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201202_1156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adminstuff',
            new_name='Rooms',
        ),
    ]
