# Generated by Django 3.1.4 on 2020-12-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201202_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('room_no', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='pics')),
                ('room_type', models.CharField(choices=[('Elt', 'Elite'), ('Lux', 'Luxury'), ('Sig', 'Signature')], max_length=3)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
