# Generated by Django 3.1.4 on 2020-12-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201202_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Lux', 'Luxury'), ('Elt', 'Elite'), ('Sig', 'Signature')], max_length=3),
        ),
    ]
