# Generated by Django 3.1.4 on 2020-12-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201202_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Sig', 'Signature'), ('Elt', 'Elite'), ('Lux', 'Luxury')], max_length=3),
        ),
    ]
