# Generated by Django 3.1.4 on 2020-12-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201202_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Sig', 'Signature'), ('Lux', 'Luxury'), ('Elt', 'Elite')], max_length=3),
        ),
    ]
