# Generated by Django 3.1.4 on 2020-12-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20201202_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_price',
        ),
        migrations.AddField(
            model_name='room_type',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='room_type',
            name='roomtype',
            field=models.CharField(choices=[('Elt', 'Elite'), ('Sig', 'Signature'), ('Lux', 'Luxury')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
