# Generated by Django 3.1.4 on 2020-12-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20201203_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_type',
            name='roomtype',
            field=models.CharField(choices=[('SIG', 'Signature'), ('ELT', 'Elite'), ('LUX', 'Luxury')], max_length=20),
        ),
    ]
